### ISSUE TITLE
Feature request: Automatic retry

### ISSUE THREAD

**Issue by ghost** [heilkit/tt#1]
When the script fails, it stops working and must be re-launched manually. It would be very useful if the script could retry the failed video and continue downloading. Thank you in advance

**Comment by heilkit** [comment]
@Feodosr sup, I've added `-retries` and `-ignore` flags for massive downloads.

Note that rarely Tikwm gives you broken source links, or it can't find you HD sources. The problem usually goes away if you retry the download after a day or download SD version of video.
